port: 8000
database:
  driver: "mysql" #possible value are mongodb or mysql # address: "127.0.0.1"
  address: "database-ku.cwid5dwr9dfn.ap-southeast-1.rds.amazonaws.com"
  port: 3306  
  username: "todosadmin"
  password: "todos123"
  name: "to_do_lists"