port: 8000
database:
  driver: "mysql" #possible value are mongodb or mysql
  address: "127.0.0.1"
  port: 3306
  #untuk docker #username = "root"
  username: "root"
  password: ""
  name: "to_do_lists"